### ISSUE TITLE
error while running the index.js

### ISSUE THREAD

**Issue by sakarimov** [JannisHajda/Schedulegram#1]
i run 'node ./node_modules/schedulegram/src/index.js' in my linux machine, and i get these error

(node:33672) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'click' of null
    at Schedulegram.login (/home/cikapc/node_modules/schedulegram/src/core/schedulegram.js:26:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:33672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cachebust** [comment]
I believe that is because it is unable to find the element as the element id has changed.

**Comment by JannisHajda** [comment]
Should be fixed. Future changes of the Creator Studio will be implemented way faster due to a change in the core of Schedulegram. Thanks for your patience!
